# Math  1376: Programming for Data Science
---

## External activities for 02-Python-basics-lecture-part-b
---

**Expected time to completion: 1 hour**

In [11]:
import numpy as np

---

##  Activity 1: Practice controlling the randomness 

We use the `random.seed` function within `numpy` below to control the reproducibility of the random numbers below. 
This should only ever be done for creating tests or debugging, but it is a good function to be aware of nonetheless. 

You should probably use Google (or whatever your favorite search engine is) to read more about the `random.seed` function within `numpy` to help you interpret results.

- Run the code cell below multiple times and comment on/interpret the results in the Markdown cell that follows.

In [17]:
# Try re-running this code cell multiple times

np.random.seed(123456)

#generate one normally distributed sample with mean 0.0 and st.dev. of 1.0
sample = np.random.normal(loc=0.0, scale=1.0) 

print()
print( sample )


0.4691122999071863


- The np.random.seed function sets the seed for the pseudorandom number generator in numpy. By setting the seed to a specific value, it ensures that the same sequence of random numbers is generated each time the code is run.

- In the code above, the seed is set to 123456 and a single random number is generated from a normal distribution with mean 0.0 and standard deviation 1.0.

- If the code cell is run multiple times, the output will always be the same random number (determined by the seed value), which is why it's not recommended to use np.random.seed in most cases. However, for testing or debugging purposes, it can be useful to ensure reproducibility of results.



- Run the first code cell below *once* and the code cell below it *multiple times* and then comment on/interpret the results in the Markdown cell that follows. 

In [18]:
# Run this code cell only once
np.random.seed(123456)

In [21]:
# Run this code cell multiple times

#generate one normally distributed sample with mean 0.0 and st.dev. of 1.0
sample = np.random.normal(loc=0.0, scale=1.0) 

print()
print( sample )


-1.5090585031735124


- The first code cell sets the seed for the pseudorandom number generator in numpy to 123456. This ensures that the same sequence of random numbers will be generated each time the second code cell is run.

-  The second code cell generates a single random number from a normal distribution with mean 0.0 and standard deviation 1.0.

- If the second code cell is run multiple times, the output will always be the same sequence of random numbers, determined by the seed value. However, if the first code cell is run multiple times (before running the second code cell), then a different seed value will be set and a different sequence of random numbers will be generated.





End of Activity 1.

---

---

##  Activity 2: Practice with using `numpy` mathematical functions

<mark> Run the code cell below  to create the array used in this activity.</mark>

In [22]:
# This code cell is completed and no interpretation is necessary 
# in a Markdown cell

# We first create my_array as a 1d array
my_array = np.array([np.e, np.pi, 3*np.pi/2, np.inf, np.NINF, np.nan, 0, 1])

# We now reshape a 1D array into a 2D array that looks like a column vector.
# This is just intended to show you one way how we can do this because it is
# sometimes convenient to represent a 1D array as a column vector instead of a 
# row vector.
my_array = my_array[:, np.newaxis]  
print(my_array)

[[2.71828183]
 [3.14159265]
 [4.71238898]
 [       inf]
 [      -inf]
 [       nan]
 [0.        ]
 [1.        ]]


You may find it useful to first look at the documentation on the [mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html) available within `numpy` as well as examining some graphs of the functions used below (these can be found with a quick Google search or on Wikipedia or other search engine).

The documentation on [constants](https://numpy.org/doc/stable/reference/constants.html) available within `numpy` may also be useful to review to understand some of the constants used in `my_array` in the code cell above and also the outputs of some of the operations in the code cells below.

- Use the code comments and print statements to guide you in filling in the missing pieces of the code cells below.

- Summarize/interpret the outputs of each of these cells in a Markdown cell following each of the code cells.

   - Make sure in your interpretation of results to explain why the evaluation of `np.inf` or `np.NINF` (whch are `numpy` constants representing the symbols $\infty$ and $-\infty$, respectively) sometimes gives `inf`,`-inf`, or a number, and other times gives `nan` (which is a `numpy` constant representing "Not a Number"). This is where an understanding of the asymptotic behavior of the functions is very useful, which can usually be inferred by examining graphs of these functions.

In [23]:
my_output = np.exp(my_array)

print('The exponential of my_array is \n\n', my_output)

print()

print('Rounding to 2 decimal places gives \n\n', np.around(my_output, 2))

The exponential of my_array is 

 [[ 15.15426224]
 [ 23.14069263]
 [111.31777849]
 [         inf]
 [  0.        ]
 [         nan]
 [  1.        ]
 [  2.71828183]]

Rounding to 2 decimal places gives 

 [[ 15.15]
 [ 23.14]
 [111.32]
 [   inf]
 [  0.  ]
 [   nan]
 [  1.  ]
 [  2.72]]


- np.exp calculates the exponential of each element in the input array my_array.
- The first print statement displays the output array my_output.
- The second print statement displays the same array my_output rounded to 2 decimal places using np.around.

In [24]:
my_output = np.sin(my_array)

print('The sine of my_array is \n\n', my_output)

print()

print('Rounding to 4 decimal places gives \n\n', np.around(my_output, 4))

The sine of my_array is 

 [[ 4.10781291e-01]
 [ 1.22464680e-16]
 [-1.00000000e+00]
 [            nan]
 [            nan]
 [            nan]
 [ 0.00000000e+00]
 [ 8.41470985e-01]]

Rounding to 4 decimal places gives 

 [[ 0.4108]
 [ 0.    ]
 [-1.    ]
 [    nan]
 [    nan]
 [    nan]
 [ 0.    ]
 [ 0.8415]]


<ipython-input-24-3ee9f9e35695>:1: RuntimeWarning: invalid value encountered in sin
  my_output = np.sin(my_array)


- np.sin calculates the sine of each element in the input array my_array.
- The first print statement displays the output array my_output.
- The second print statement displays the same array my_output rounded to 4 decimal places using np.around.


In [25]:
my_output = np.log(my_array)

print('The (natural) logarithm of my_array is \n\n', my_output)

print()

print('Rounding to 3 decimal places gives \n\n', np.around(my_output, 3))

The (natural) logarithm of my_array is 

 [[1.        ]
 [1.14472989]
 [1.55019499]
 [       inf]
 [       nan]
 [       nan]
 [      -inf]
 [0.        ]]

Rounding to 3 decimal places gives 

 [[1.   ]
 [1.145]
 [1.55 ]
 [  inf]
 [  nan]
 [  nan]
 [ -inf]
 [0.   ]]


<ipython-input-25-b8e64391c991>:1: RuntimeWarning: divide by zero encountered in log
  my_output = np.log(my_array)
<ipython-input-25-b8e64391c991>:1: RuntimeWarning: invalid value encountered in log
  my_output = np.log(my_array)


- np.log calculates the natural logarithm of each element in the input array my_array.
- The first print statement displays the output array my_output.
- The second print statement displays the same array my_output rounded to 3 decimal places using np.around.

End of Activity 2.

---

---

## Activity 3: Creating arrays of different shapes

- Fill in the code cells below to create a 2D array of shape (3, 1) and a 3D array of shape (4, 3, 1).

In [13]:
# Create a 2D array with the values 1, 2, and 3

my_array_2d = np.array( [ [1],[2],[3] ] )

# Print the created array

print()
print( 'my_array_2d =\n', my_array_2d )

# Print the shape of the created array

print()
print( 'The shape of my_array_2d is', my_array_2d.shape )


my_array_2d =
 [[1]
 [2]
 [3]]

The shape of my_array_2d is (3, 1)


In [15]:
# Create a 3D array

my_array_3d = np.array( [ [[1],[2],[3]],
                         [[4],[5],[6]],
                         [[7],[8],[9]],
                         [[10],[11],[12]] ] )

# Print the 3D array

print()
print( 'my_array_3d =\n', my_array_3d )

# Print the shape of the 3D array

print()
print( 'The shape of my_array_3d is', my_array_3d.shape )


my_array_3d =
 [[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]

The shape of my_array_3d is (4, 3, 1)


End of Activity 3.

---